<?php

namespace Ypsylon\Propel\Behavior\I18NVersionable;

use Propel\Generator\Behavior\I18n\I18nBehavior;
use Propel\Generator\Model\PropelTypes;

class I18NVersionableBehavior extends I18nBehavior
{

    public function __construct()
    {
        $this->parameters['versionable'] = 'true';
        $this->parameters['log_created_at'] = 'false';
        $this->parameters['log_create_by'] = 'false';
        $this->parameters['log_comment'] = 'false';
    }

    protected function addLocaleColumnToI18n()
   {
       $localeColumnName = $this->getLocaleColumnName();

       if (! $this->i18nTable->hasColumn($localeColumnName)) {
           $this->i18nTable->addColumn([
               'name'       => $localeColumnName,
               'type'       => PropelTypescd ::VARCHAR,
               'size'       => $this->getParameter('locale_length') ? (int) $this->getParameter('locale_length') : 5,
               'default'    => $this->getDefaultLocale(),
           ]);
       }
   }

   public function modifyTable()
   {
       parent::modifyTable(); // TODO: Change the autogenerated stub

       if ($this->getParameter('versionable')) {
           $versionParams = [];
           $versionParams['log_created_at'] = $this->getParameter('log_created_at');
           $versionParams['log_create_by'] = $this->getParameter('log_created_by');
           $versionParams['log_comment'] = $this->getParameter('log_comment');

           $versionBehavior = new VersionableBehavior();
           $versionBehavior->setParameters($versionParams);
           $this->i18nTable->addBehavior($versionBehavior);
       }
   }
}